### ISSUE TITLE
Can't use formula as branch

### ISSUE THREAD

**Issue by alexpearce** [ibab/root_pandas#14]
`root_numpy` supports using formula as branch names. For example:

```python
>>> root_numpy.root2array('f.root', 'tree', branches=['sqrt(mass)'], stop=3)
array([(739.8708446958261,), (1225.6622271912993,), (1096.497904427192,)],
      dtype=[('sqrt(mass)', '<f8')])
```

`root_pandas` doesn't support this, because it [pattern matches branch names](https://github.com/ibab/root_pandas/blob/bf7ba3ca3c27ee3c8a6cf667325e453bc17e9140/root_pandas/readwrite.py#L62-L63), failing if a name in the `branches` argument doesn't match a `TBranch` in the `TTree`.

**Comment by ibab** [comment]
Would you suggest that we silently ignore patterns that don't match and let root_numpy fail if it doesn't find something?

It seems like we can't have both branch name matching and formulas in branch names, as the `*` in `a * b` would apply to both things at once.

**Comment by alexpearce** [comment]
> It seems like we can't have both branch name matching and formulas in branch names, as the * in a * b would apply to both things at once.

Indeed. I really like the globbing and brace expansion, so I'd be sad to see that go.

Maybe if formulas had to be prefixed with some magic string? Like `formula:sqrt(mass)`. Then anything with the prefix would be ignored by the expansion logic, and the prefix is stripped before being passed to `root_numpy`.

It's not ideal though, and would require explicit documentation (although the support for formula is isn't mentioned in the `root_numpy.root2array` docs…).

**Comment by ibab** [comment]
A `noexpand:` prefix would make a lot of sense, especially for cases where your variable names contain braces and `*`.

**Comment by alexpearce** [comment]
:+1: for `noexpand:`.

It's pretty obvious what `noexpand:` should do and why, whereas understanding an `expand` kwarg requires you understanding the internals a bit more.
