### ISSUE TITLE
Pipi sticker doesn't link to pipi

### ISSUE THREAD

**Issue by KonstantinSchubert** [ibab/root_pandas#16]
Clicking on the pipi sticker in the Readme, I get a 404.

In fact I cannot find root-pandas on pipi any more: 
https://pypi.python.org/pypi?%3Aaction=search&term=root-pandas&submit=search

**Comment by remenska** [comment]
It's with underscore, not a dash:

https://pypi.python.org/pypi?%3Aaction=search&term=root_pandas&submit=search

**Comment by KonstantinSchubert** [comment]
Right. But the pipi sticker still doesn't work...
https://github.com/ibab/root_pandas/blob/master

**Comment by ibab** [comment]
I forgot to add the link to the button.
Thanks for spotting this!
