### ISSUE TITLE
Put the package on pypi

### ISSUE THREAD

**Issue by MaxNoe** [ibab/root_pandas#9]
Just upload it :) 

Makes installing easier.

**Comment by ibab** [comment]
There are currently several problems with the package that I would like to solve before uploading it.
For example, there should be a way to access arrays more conveniently.

**Comment by KonstantinSchubert** [comment]
If it was up on pypi it would be easier to handle it as a dependency http://mike.zwobble.org/2013/05/adding-git-or-hg-or-svn-dependencies-in-setup-py/

**Comment by ibab** [comment]
I was thinking of making some last backwards incompatible changes before doing that

**Comment by cdeil** [comment]
Just saw this package ... thanks @ibab!

As an alternative to releasing / maintaining this as a separate package, why not put it in `root_numpy` and develop / maintain it there?

**Comment by ibab** [comment]
In that case, `pandas` would become a dependency of `root_numpy`.
It could be implemented as a soft dependency, but I think having it as a separate project would be nicer.
I wouldn't mind adding the package to the `rootpy` organization.

**Comment by ndawe** [comment]
+1 for keeping it a separate project since it serves a distinct purpose. Also, adding root_pandas to the rootpy organization would be very welcome!

**Comment by ibab** [comment]
The package has been on PyPI for a few days now.

**Comment by MaxNoe** [comment]
Very nice. Thanks a lot!
